### ISSUE TITLE
Consider unit system from scikit-hep

### ISSUE THREAD

**Issue by tunnell** [JelleAalbers/strax#4]
https://github.com/scikit-hep/scikit-hep

**Comment by JelleAalbers** [comment]
That's an interesting package; we may also be able to use their Dataset classes, ideally scikit-hep packages could then operate directly on strax's output files.

I think we'd want to keep the strax core, plugin system etc. in this repo, and have another one for XENON-specific code (and others for other experiments). Then in this repo we won't need a unit system other than for time (ns = 1 as in pax and scikit-hep).

**Comment by tunnell** [comment]
Looking through, it actually doesn't seem that useful for us.  The units and constants maybe... but that should be it's own package instead of making a new ROOT-like mega-package.

Will close.
